@SYSOP@ welcomes you to @BBS@!

You're here early - we're under construction, but feel free to look around, there's a massive amount of customization on this BBS.  One of the things you may find interesting is you can use your mouse to navigate most of the BBS.

We're creating our own GUI for synchronet (our bbs software platform) so it doesn't look like any other BBS'ses, and recreating a lot of core stuff to run inside that and work with mouse events, and that takes a little time, testing and patience.  Not too much, but a little.

Also with a GUI, we've got to have great art for icons, and our art is currently mediocre as I'm not a great artist.

Then of course also coming is all the stuff you'd expect from a typical sysop, stuff like this, plugging in a welcome email.

Since you're here early, it's possible the sysop may be developing it when you login, adding features in a live environment is bound to trigger some runtime errors.  In other words, you may be logging in while I'm coding, and right now I'm just coding on the box that runs the code (the BBS).  So my coding errors are yours until I launch the BBS or change my workflow.  If an error happens, it's corrected immediately but you may see things happen in real time.  

If you get kicked out of the shell just hit "R" to re-enter, I may have squased the bug or wait a few minutes and I probably will have.

YEP, this long winded.

WE'RE UNDER CONSTRUCTION


